
language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run deploy
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: 7f6fe58451666d11ee14fab2e767520c3a7a8d8b
  
  # Set in the settings page of your repository, as a secure variable